# Generated by Django 3.2.7 on 2024-03-28 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='consult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('did', models.CharField(max_length=150)),
                ('uid', models.CharField(max_length=150)),
                ('date', models.CharField(max_length=150)),
                ('des', models.CharField(max_length=150)),
                ('file', models.CharField(max_length=150)),
                ('status', models.CharField(max_length=150)),
                ('medicine', models.CharField(max_length=150)),
                ('prescription', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=150)),
                ('age', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=150)),
                ('specialization', models.CharField(max_length=150)),
                ('experience', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=150)),
                ('status', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='remedy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('emotion', models.CharField(max_length=150)),
                ('stress_level', models.CharField(max_length=150)),
                ('music', models.CharField(max_length=150)),
                ('video', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='result_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=150)),
                ('uid', models.CharField(max_length=150)),
                ('emotion', models.CharField(max_length=150)),
                ('stress', models.CharField(max_length=150)),
                ('mode', models.CharField(max_length=150)),
            ],
        ),
    ]
